services:
  ibm-fhir:
    image: ibmcom/ibm-fhir-server:4.11.1
    ports:
      - 9080:9080
      - 9443:9443
    volumes:
      - './ibm-fhir-config/server.xml:/opt/ol/wlp/usr/servers/defaultServer/server.xml'
      - './ibm-fhir-config/userlib/:/opt/ol/wlp/usr/servers/defaultServer/userlib'
    environment:
      BOOTSTRAP_DB: true
      FHIR_USER_PASSWORD: supersecret
      FHIR_ADMIN_PASSWORD: extrasecret
