fhirclient:
  logging:
    enabled: 'false'

lifecycle:
  on-startup:
    bootstrap: false

quarkus:
  http:
    port: '8080'
    ssl-port: '8443'
    insecure-requests: redirect

  keycloak:
    policy-enforcer:
      enable: true
