fhirclient:
  rest:
    base:
      url: 'http://localhost:9080/fhir-server/api/v4'
  basicauth:
    enabled: 'true'
    username: 'fhiruser'
    password: 'supersecret'
  logging:
    enabled: 'false'

quarkus:
  oidc:
    auth-server-url: 'https://localhost:8443/realms/quarkus'
    client-id: 'backend-service'
    credentials:
      secret: 'secret'
    tls:
      verification: 'none'

  keycloak:
    policy-enforcer:
      enable: true
