package org.fhirvp.model;

public enum FHIRResourceType {

    PATIENT,
    PRACTITIONER,
    IMMUNIZATION,
    IMMUNIZATION_RECOMMENDATION,
    MEDICATION,
    ORGANIZATION,

    VACATION_PLAN,
    ACTIVE_VACCINATION_SCHEME,
    POPULATION_RECOMMENDATION,
    TARGET_DISEASE,
    VACCINATION_SCHEME,
    VACCINATION_DOSE,

    UNKNOWN

}
