name: Docker Image Build

on:
  workflow_call:
    inputs:
      image-group:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        env:
          QUARKUS_CONTAINER_IMAGE_BUILD: true
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_GROUP: ${{ inputs.image-group }}
          QUARKUS_CONTAINER_IMAGE_NAME: ${{ inputs.image-name }}
          QUARKUS_CONTAINER_IMAGE_TAG: ${{ inputs.image-tag }}
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_DOCKER_CACHE_FROM: ghcr.io/${{ inputs.image-group }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          QUARKUS_DOCKER_BUILDX_PLATFORM: linux/amd64,linux/arm64
        run: |
          docker pull ghcr.io/${{ inputs.image-group }}/${{ inputs.image-name }}:${{ inputs.image-tag }} || true
          ./gradlew --info build
